### ISSUE TITLE
Absence of gamma correction code

### ISSUE THREAD

**Issue by Alice206** [yangyiliu21/ntire2023_ITBdehaze#4]
Hello, thank you for your outstanding work, could you please share the code about the part of your work that uses gamma correction to enlarge the dataset? At the same time, if you have NH-HAZE2020, NH-HAZE2021 and NH-HAZE2023 original datasets, is it convenient to share? I would appreciate it so much!

**Comment by yangyiliu21** [comment]
Please check the new readme

**Comment by Alice206** [comment]
Thank you, may I ask what is your idea or method for the value of gamma factor?

**Comment by yangyiliu21** [comment]
We empirically tested and found the gamma value that adjust mean to be close to the mean of data of 2023

**Comment by Alice206** [comment]
Hello, I had some problems when calculating the average pixel intensity of the NH-HAZE23 training set. When calculating only hazy images, the values are around 147 (R), 174 (G), 200(B). And when GT images are included, the values are around 125(R), 142 (G), 148 (B). Both the values are different from the results presented in the paper. Is there any work not mentioned in the paper or do you have any suggestions? Thanks sincerely.

**Comment by yangyiliu21** [comment]
For 2023 data, the mean we calculated for the original hazy data are 145(R), 170(G), 192(B); for GT data are 107(R), 114(G), 101(B). We used cv2.imread to read in the input (the order is B-G-R for channel 0-1-2).  Could you please check if your downloaded 2023 data is 40 pairs of 4k*6k (or 6k*4k) images? Cheers

**Comment by Alice206** [comment]
Sorry for the late reply. Yes, you are right! Maybe there was something wrong with the image rotation earlier. Thanks. Have a nice day!

**Comment by yangyiliu21** [comment]
No worries. Thanks for the updates.
